#端口号
server:
  port: 8080
#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.60.15.19:3306/ogs?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  mvc:
      view:
        prefix: "/"
        suffix: ".jsp"
mybatis:
  type-aliases-package: com.ogs.domain

obs:
  endPoint: obs.cn-north-4.myhuaweicloud.com
  ak: E9MOTADUKWHLBSPKRBO1
  sk: 1cz6rCBX3djJKc9yuTHFaHrBNFuL5nLqgtUtF966
  bucketLocation: cn-north-4
  bucketName: obs-ogs
